### ISSUE TITLE
warning: command substitution: ignored null byte in input

### ISSUE THREAD

**Issue by Torxgewinde** [trsqr/mijia_mqtt#1]
Hello Olli,
I had to add a command to get rid of the message in the title on bash version 5.03. The "tr -d '\0' removes null bytes which somehow were triggering these warnings:

...
humid=$(echo $data | tail -1 | grep -oP 'value: \K.*' | xxd -r -p | cut -f 2 -d" " | cut -f 2 -d"=" | tr -d '\0')
...

Thanks for that helpful script!

Kind regards,
Tom

**Comment by trsqr** [comment]
Thanks! Fixed now.
